GET http://localhost:3001/api/blogs

####

POST http://localhost:3001/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iktpc3NhIiwiaWQiOjIsImlhdCI6MTY1ODcwOTQ3NH0.MoukfqA7A4oKWrN3aO83f0AqlvqqEDsyNn-dgY1DzwA

{
  "author": "kissa", 
  "url": "a", 
  "title": "koira"
}

#####

DELETE http://localhost:3001/api/blogs/15
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthdHRpIiwiaWQiOjEsImlhdCI6MTY1ODcwNzcxMX0.v_wJk0s_bArP3GDuuC3lzzkuUJFLCuLyVBxa6l7wuSs

####

PUT http://localhost:3001/api/blogs/16
Content-Type: application/json

{
  "likes": 2
}

####

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "koira@gmail.com", 
  "name": "Koira2"
}

####

GET http://localhost:3001/api/users

#####

PUT http://localhost:3001/api/users/Kissa
Content-Type: application/json

{
  "username": "Katti"
}


#####

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Kissa",
  "password": "salainen"
}
